// SPDX-License-Identifier: GPL-3.0-or-later
// DSperate - Nintendo DS emulator. Copyright (C) 2026 DSperate contributors.
#include "core/gpu/vk/vk_shaders.h"

// The compute shaders, linked in as SPIR-V with .incbin rather than compiled
// at build time: the blobs are generated by tools/gen_shaders.sh and tracked
// beside their .comp sources, so building the emulator needs no shader
// compiler. Same shape as io/dsi_font.cpp's font tables, and the CMake rule
// beside it re-links when a .spv changes.
//
// Edit a .comp, run tools/gen_shaders.sh, commit both.

#define DS_INCBIN(sym, file)                                     \
  __asm__(".section .rodata\n"                                   \
          ".balign 4\n"                                          \
          ".globl " #sym "_data\n"                               \
          #sym "_data:\n"                                        \
          ".incbin \"" DSPERATE_VK_SHADER_DIR "/" file "\"\n"    \
          ".globl " #sym "_end\n"                                \
          #sym "_end:\n"                                         \
          ".previous\n");                                        \
  extern "C" const unsigned char sym##_data[], sym##_end[]

DS_INCBIN(ds_vk_bin, "bin.spv");
DS_INCBIN(ds_vk_raster, "raster.spv");
DS_INCBIN(ds_vk_post, "post.spv");
DS_INCBIN(ds_vk_span, "span.spv");
DS_INCBIN(ds_vk_vis, "vis.spv");
DS_INCBIN(ds_vk_raster_vis, "raster_vis.spv");
DS_INCBIN(ds_vk_tri_vert, "tri_vert.spv");
DS_INCBIN(ds_vk_tri_opaque, "tri_opaque_frag.spv");
DS_INCBIN(ds_vk_tri_tail, "tri_tail_frag.spv");

namespace ds::gpu::vk {

Spirv shader_bin() {
  return { reinterpret_cast<const u32*>(ds_vk_bin_data),
           static_cast<size_t>(ds_vk_bin_end - ds_vk_bin_data) };
}

Spirv shader_raster() {
  return { reinterpret_cast<const u32*>(ds_vk_raster_data),
           static_cast<size_t>(ds_vk_raster_end - ds_vk_raster_data) };
}

Spirv shader_span() {
  return { reinterpret_cast<const u32*>(ds_vk_span_data),
           static_cast<size_t>(ds_vk_span_end - ds_vk_span_data) };
}

Spirv shader_post() {
  return { reinterpret_cast<const u32*>(ds_vk_post_data),
           static_cast<size_t>(ds_vk_post_end - ds_vk_post_data) };
}

Spirv shader_vis() {
  return { reinterpret_cast<const u32*>(ds_vk_vis_data),
           static_cast<size_t>(ds_vk_vis_end - ds_vk_vis_data) };
}

Spirv shader_raster_vis() {
  return { reinterpret_cast<const u32*>(ds_vk_raster_vis_data),
           static_cast<size_t>(ds_vk_raster_vis_end - ds_vk_raster_vis_data) };
}

Spirv shader_tri_vert()   { return { reinterpret_cast<const u32*>(ds_vk_tri_vert_data),   static_cast<size_t>(ds_vk_tri_vert_end - ds_vk_tri_vert_data) }; }
Spirv shader_tri_opaque() { return { reinterpret_cast<const u32*>(ds_vk_tri_opaque_data), static_cast<size_t>(ds_vk_tri_opaque_end - ds_vk_tri_opaque_data) }; }
Spirv shader_tri_tail()   { return { reinterpret_cast<const u32*>(ds_vk_tri_tail_data),   static_cast<size_t>(ds_vk_tri_tail_end - ds_vk_tri_tail_data) }; }

} // namespace ds::gpu::vk
