#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Regenerate the pause menu's Chinese face, src/frontend/sdl/font_cn_data.inc.

    make_menu_font.py [-o OUT.inc] [--stats] source.ttf|source.ttc

The menu draws its rows with a compiled-in 5x7 bitmap font, which has room for
an ASCII capital and nothing like room for a Han character. So the menu carries
a second face -- rasterised at draw time by stb_truetype -- and this is the
script that puts it there.

It writes a subset: only the code points the menu can actually be asked to
draw. Full Noto/WenQuanYi coverage would be several megabytes of binary for
glyphs that no row will ever name, and a handheld notices that. Two sets are
collected:

  - every GB 2312 level-1 character (3755 of them, the common ones), so a ROM's
    own Chinese title -- which the frontend reads out of the cartridge header
    and hands to the game picker as a list row -- draws instead of falling back
    to '?'; and
  - every non-ASCII code point appearing in the menu's own sources, which is
    the part that has to be complete: a missing UI glyph is a hole in a page.

Usage -- where anything drawn in the menu is going to be incomplete without it:

  - Adding or editing a string in src/frontend/sdl/menu.cpp or settings.cpp
    that contains Chinese punctuation, arrows, or a character GB 2312 level 1
    does not carry (a full-width form, a symbol).
  - Trading size for coverage, or the other way round.

Requirements: fonttools (pip install fonttools). The source must be a TrueType
face with glyf outlines -- stb_truetype rasterises glyf and cannot read a CFF
font, which is why Noto Sans CJK is not usable here and WenQuanYi Micro Hei
(the same face tools/make_dsi_font.py already rasterises its own Chinese from)
is.
"""
import argparse
import os
import re
import subprocess
import sys

# The tables stb_truetype actually reads, kept in their required order (the
# spec's order, which is also the order they appear in every real file).
#
# Dropping the rest is most of the saving. A font carries tables nobody will
# use at a menu -- GSUB/GPOS layout for scripts this menu never shapes, 'name'
# strings in seven languages, hinting programs for a rasteriser that ignores
# hints -- and together they are as many bytes again as the outlines.
KEEP_TABLES = ["cmap", "glyf", "head", "hhea", "hmtx", "loca", "maxp"]

# Where the face comes from. Recorded the way tools/make_dsi_font.py records
# its own inputs -- the distribution package, the file inside it, and the
# SHA-256 of exactly the bytes that were used -- so that a regeneration is
# something you can check rather than take on trust. This is the same face, at
# the same version, as the one already shipped under src/core/io/dsi_font/.
#
# Take the file from that package rather than from anywhere else. The
# SourceForge tarball of the same 0.2.0-beta release hashes differently, and a
# different hash means different outlines, so a font built from it is not the
# font this table says it is.
SOURCES = [
    {
        "file": "wqy-microhei.ttc",
        "package": "Debian/Ubuntu fonts-wqy-microhei 0.2.0-beta-3.1",
        "inside": "/usr/share/fonts/truetype/wqy/wqy-microhei.ttc",
        "sha256": "2420e8078af796b19a3f6ef13de527a1a91c1e7171eea115926c614ced1009b3",
    },
]

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SDL_DIR = os.path.join(REPO_ROOT, "src", "frontend", "sdl")
# Every code point these files can hand to draw_text() at runtime. Reading the
# sources rather than keeping a list is what stops the subset drifting out of
# step with the strings it was built for. tr_data.inc holds the localization
# table (the Chinese strings the menu shows after tr_text()), so it must be
# scanned too -- otherwise new Chinese added in translation would render as ?.
TEXT_SOURCES = [os.path.join(SDL_DIR, n) for n in ("menu.cpp", "settings.cpp", "tr_data.inc")]

HEADER = """\
// SPDX-License-Identifier: GPL-3.0-or-later
// Generated by tools/make_menu_font.py -- do not edit.
// Source: %(source)s, %(package)s
//         SHA-256 %(sha256)s
//         subset to GB 2312 level-1 plus the code points the menu and the
//         localization table (tr_data.inc) use.
//         Same face, same version, as the one in src/core/io/dsi_font/.
//         %(license)s
#pragma once
// The embedded TrueType face, as one byte array. It travels in the
// binary rather than beside it: the menu has no asset path to look in,
// and a handheld has nowhere to put one.
static const unsigned char kMenuFontData[] = {
"""

FOOTER = """\
};

static const unsigned int kMenuFontLen = sizeof(kMenuFontData);
"""


def die(msg):
    sys.stderr.write("make_menu_font.py: %s\n" % msg)
    raise SystemExit(1)


def recorded_source(path):
    """The SOURCES entry for `path`, if the bytes match the recorded hash.

    Returns the entry, or None. A face whose hash is not in the table is still
    usable -- someone may have a newer release -- but it is not the face this
    file documents, so the caller is told and the hash is still written into
    the header below, where the next person can compare it.
    """
    import hashlib
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    digest = h.hexdigest()
    for rec in SOURCES:
        if os.path.basename(path) == rec["file"] and digest == rec["sha256"]:
            return rec, digest
    return None, digest


def cpp_char_ranges(path):
    """The non-ASCII code points a C++ source can draw.

    Scans string literals only, so a Chinese comment does not put a glyph in
    the binary. Reads the file as UTF-8, which is what these sources are --
    menu.cpp's own text layer decodes UTF-8, and a file written in anything
    else would be a file whose literals are not the bytes the menu receives.
    """
    with open(path, encoding="utf-8") as f:
        text = f.read()

    # One regex rather than a state machine: a string literal is what is being
    # looked for, and the escapes that could confuse this (\" and \\) are two
    # cases a character class handles. Adjacent pieces are then rejoined, so
    # "保存" "存档" reads as one string the way the compiler reads it.
    pieces = re.findall(r'"((?:[^"\\]|\\.)*)"', text, re.S)
    cps = set()
    for piece in pieces:
        # Undo the escapes the compiler would undo. Anything else (a \x bytes,
        # a face-button pip) is ASCII by construction and not this script's
        # business -- those already have glyphs in the 5x7 grid.
        decoded = re.sub(r"\\(.)", lambda g: g.group(1), piece)
        for ch in decoded:
            if ord(ch) >= 0x2E80:      # the floor menu.cpp uses to pick a path
                cps.add(ord(ch))
    return cps


def ascii_printable():
    """Every printable ASCII code point, 0x20..0x7E.

    Method 1 of the font-unification work routes *every* code point the menu
    can name -- Latin included -- through this same TrueType face at the 7px
    box, so English and Chinese are one engine at one size. That only works if
    the face actually carries the ASCII glyphs, which the original subset
    deliberately skipped (they were the 5x7 grid's job). With them present,
    draw_text's first choice (the embedded face) is the only path English ever
    takes, and the 5x7 bitmap is pure fallback for the glyphs nobody put in.
    """
    return list(range(0x20, 0x7F))


def gb2312_level1():
    """GB 2312 level-1 Han: 3755 common characters, ordered by its own layout.

    Level 1 rather than both levels because these are the characters Chinese
    text actually uses, and level 2 would double the binary for rare
    surname and place-name glyphs a ROM title is unlikely to carry. A game
    title that reaches past this still draws as '?' rather than crashing --
    which is what drew before there was a face at all.
    """
    out = []
    # Rows 16..55 of the 94x94 grid are level 1; each row carries 94 characters.
    for row in range(16, 56):
        for cell in range(1, 95):
            # The EUC-CN pair -> Unicode conversion: add 0xA0 to each byte. A
            # handful of grid positions are holes in the standard (undefined),
            # which the codec refuses; they carry no character so skipping them
            # loses nothing -- a ROM title that names one still reads as '?'.
            pair = bytes([row + 0xA0, cell + 0xA0])
            try:
                out.append(ord(pair.decode("gb2312")))
            except UnicodeDecodeError:
                pass
    return out


def build_subset(font_path, codepoints):
    """Write a subsetted TrueType file and return its bytes."""
    try:
        from fontTools import subset
    except ImportError:
        die("fonttools is required: pip install fonttools")

    ordered = sorted(codepoints)
    options = subset.Options()
    # No layout, no hinting, no OpenType features: stb reads outlines and
    # advances and nothing else, and dropping what it cannot read is what
    # makes this small enough to compile in.
    options.drop_tables = list(getattr(subset.Options, "default_drop_tables", [])) + [
        "GSUB", "GPOS", "GDEF", "gasp", "name", "post", "prep", "cvt ",
        "fpgm", "FFTM", "DSIG", "LTSH", "PCLT", "VDMX", "vhea", "vmtx",
    ]
    options.passthrough_tables = []
    # A .ttc is a collection; take its first face (WenQuanYi Micro Hei).
    options.font_number = 0
    options.layout_features = []
    options.name_IDs = ["*"]
    options.notdef_outline = True
    options.recalc_bounds = True
    options.glyph_names = False
    options.recalc_average_width = True
    options.drop_names = True

    font = subset.load_font(font_path, options)
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=ordered)
    subsetter.subset(font)

    from fontTools.ttLib import TTFont
    import io
    buf = io.BytesIO()
    font.save(buf)
    return buf.getvalue()


def c_array(data, per_line=16):
    lines = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        lines.append("  " + ", ".join("0x%02x" % b for b in chunk) + ",")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("source", nargs="?",
                    help="TrueType source face (a .ttc picks its first font)")
    ap.add_argument("-o", "--out",
                    default=os.path.join(SDL_DIR, "font_cn_data.inc"),
                    help="where to write the .inc (default: %(default)s)")
    ap.add_argument("--license", default="WenQuanYi Micro Hei, GPL-3.0-or-later "
                                         "with the font exception",
                    help="the line the header credits (default: WenQuanYi Micro Hei)")
    ap.add_argument("--stats", action="store_true",
                    help="print what was collected and drawn from it, and stop")
    ap.add_argument("--where", action="store_true",
                    help="print where a recorded source face comes from, and stop")
    args = ap.parse_args()

    if args.where:
        for rec in SOURCES:
            print("%s  %s  %s" % (rec["sha256"], rec["package"], rec["inside"]))
        return

    if args.source is None:
        ap.error("give a source face, or --where to see the recorded one")

    if not os.path.isfile(args.source):
        die("no such font: %s" % args.source)

    rec, digest = recorded_source(args.source)
    if rec is None:
        print("make_menu_font.py: %s is not the recorded face (SHA-256 %s;"
              % (os.path.basename(args.source), digest))
        print("                    this is %s, whose hash is not in SOURCES."
              % SOURCES[0]["package"])
        print("                    Building anyway; the hash goes in the header,")
        print("                    and the diff against upstream will show it.")

    # What the menu can be asked to draw.
    used = set()
    for path in TEXT_SOURCES:
        if not os.path.isfile(path):
            die("missing menu source: %s" % path)
        used |= cpp_char_ranges(path)
    gb = set(gb2312_level1())
    ascii_cps = set(ascii_printable())
    all_cps = used | gb | ascii_cps

    if args.stats:
        missing = sorted(c for c in used if c not in gb)
        print("code points in the menu's own strings : %d" % len(used))
        print("GB 2312 level-1 characters           : %d" % len(gb))
        print("printable ASCII (Method 1 unification): %d" % len(ascii_cps))
        print("subset total                         : %d" % len(all_cps))
        if missing:
            print("in the menu but not in GB 2312 level 1 (%d):" % len(missing))
            print("  " + "".join(chr(c) for c in missing))
        return

    print("collecting %d code points (%d from the menu, %d GB 2312 level 1)"
          % (len(all_cps), len(used - gb), len(gb)))
    data = build_subset(args.source, all_cps)
    print("subset font: %d bytes" % len(data))

    with open(args.out, "w", encoding="utf-8") as f:
        f.write(HEADER % {"source": os.path.basename(args.source),
                          "package": rec["package"] if rec else
                                     "an unrecorded face (SHA-256 %s)" % digest,
                          "sha256": digest,
                          "license": args.license})
        f.write(c_array(data))
        f.write(FOOTER)
    print("wrote %s (%d bytes, %d-byte font -> %d bytes of C source)"
          % (args.out, os.path.getsize(args.out), len(data), os.path.getsize(args.out)))


if __name__ == "__main__":
    main()
